### ISSUE TITLE
Not compatibel with laravel 9

### ISSUE THREAD

**Issue by koencg** [druc/laravel-langscanner#6]
Only one of these can be installed: illuminate/contracts[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.2, v9.0.0, ..., v9.2.0], laravel/framework[v9.1.0, v9.2.0]. laravel/framework replaces illuminate/contracts and thus cannot coexist with it.

**Comment by mucenica-bogdan** [comment]
+1

**Comment by druc** [comment]
Added lv9 support in `1.1.0`

**Comment by zdarin** [comment]
Hi today installed your package 1.1v on laravel 9.7 not working need fix path ??

`
   Symfony\Component\Finder\Exception\DirectoryNotFoundException 

  The "User/Project/resources/lang" directory does not exist.

  at vendor/symfony/finder/Finder.php:590
    586▕             } elseif ($glob = glob($dir, (\defined('GLOB_BRACE') ? \GLOB_BRACE : 0) | \GLOB_ONLYDIR | \GLOB_NOSORT)) {
    587▕                 sort($glob);
    588▕                 $resolvedDirs[] = array_map([$this, 'normalizeDir'], $glob);
    589▕             } else {
  ➜ 590▕                 throw new DirectoryNotFoundException(sprintf('The "%s" directory does not exist.', $dir));
    591▕             }
    592▕         }
    593▕ 
    594▕         $this->dirs = array_merge($this->dirs, ...$resolvedDirs);

      +18 vendor frames 
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))`

**Comment by druc** [comment]
@zdarin I forgot the `lang` directory was moved to the root of the project. Pushed an update that should fix that. 

```
composer require druc/laravel-scanner:^2.0
```

Thanks for reporting the issue! 👍

**Comment by zdarin** [comment]
@druc :) you are welcome

**Comment by atefBB** [comment]
> druc/laravel-scanner

package name should be `druc/laravel-langscanner` ?
