### ISSUE TITLE
v-for trans(array) missing feature

### ISSUE THREAD

**Issue by zdarin** [druc/laravel-langscanner#9]
Hi, today recognised that langscanner wont add translation keys to files if they in array maybe some idea to add this feature too ??

```
  <div v-for="key in keys" :key="key">
      {{ trans(key.name) }}
   </div>
```

**Comment by druc** [comment]
@zdarin Unfortunately there is no easy way of doing this. 

The package works by scanning project files for translation function calls like `@trans()`, `trans()`, `__()` and grabbing whatever is passed as parameter. 

If the parameter is a dynamic value/variable (either vue or php), it won't be able to determine the value of that variable - and, as far as I know, there is no way of doing this :(

**Comment by zdarin** [comment]
@druc  understand thx
